# Generated by Django 5.2.5 on 2025-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('ailments', models.TextField(help_text='Comma-separated ailments')),
                ('growth_conditions', models.TextField()),
                ('image', models.ImageField(upload_to='herbs/')),
            ],
        ),
    ]
